Update readme
openinfradev/tks-info pull request #42
Opened 2022-04-14 06:40 UTC by ktkfree

README 파일 업데이트합니다.
( 재상님 알려주신 렌더링 사이트: https://stackedit.io/app# )

2022-04-14 06:47 UTC, Jaesang approved these changes

2022-04-14 06:47 UTC, Jaesang commented on README.md
> +  ```
func부터 인덴트가 들어와있는데 import처럼 맨 앞에 맞춰야하지 않나요?

2022-04-14 06:47 UTC, Jaesang commented on README.md
> +```
코드블락 뒤에 go 를 쓰면 더 좋을것같습니다.
\`\`\`go
블라블라
\`\`\`

2022-04-14 06:48 UTC, Jaesang requested changes
request changes를 누른다는게 approve를 눌렀네요ㅋ 위에 코멘트달았습니다~

2022-04-14 07:35 UTC, ktkfree commented on README.md
> +```
이런 좋은 기능이...

2022-04-18 00:45 UTC, robertchoi80 commented on README.md
> +TKS는 TACO Kubernetes Service의 약자로, SK Telecom이 만든 GitOps기반의 서비스 시스템을 의미합니다. 그 중 tks-info는 MSA 기반의 api 플랫폼 중 하나로 사용자 클러스터 및 서비스를 관리하는 컴포넌트입니다.
TKS =  'MSA 기반의 api 플랫폼(서비스)' 인데, 두번째 문장에서 뭔가 새로운 플랫폼을 얘기하는 듯한 느낌이 있고, 사용자 클러스터 및 서비스를 관리한다는 표현은 TKS 전체에 해당되는 too general 한 설명이라 '데이터'나 '정보'라는 말 등으로 tks-info의 역할을 좀더 한정시키는게  좋을 것 같습니다.

2022-04-18 05:50 UTC, Jaesang requested changes

2022-04-18 05:50 UTC, Jaesang commented on README.md
> +```
이거 추가하시는거아니였나요?ㅎ

2022-04-18 05:50 UTC, Jaesang commented on README.md
> +    docker run -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=password -d postgres
다른 코드부분과 동일하게 `$`가 앞에 추가되는게 좋겠습니다.

2022-04-18 05:58 UTC, ktkfree commented on README.md
> +TKS는 TACO Kubernetes Service의 약자로, SK Telecom이 만든 GitOps기반의 서비스 시스템을 의미합니다. 그 중 tks-info는 MSA 기반의 api 플랫폼 중 하나로 사용자 클러스터 및 서비스를 관리하는 컴포넌트입니다.
매니저님이 작성하신 README 와 어감을 맞추었습니다

2022-04-18 05:58 UTC, ktkfree commented on README.md
> +```
push 를 안했었네요. 변경하였습니다

2022-04-18 05:59 UTC, ktkfree commented on README.md
> +    docker run -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=password -d postgres
변경하였씁니다

2022-04-18 08:46 UTC, robertchoi80 approved these changes

2022-04-20 04:39 UTC, ktkfree commented
@Jaesang 
requested changes 상태로 되어 있는데 확인 부탁 드립니다

2022-04-20 04:41 UTC, Jaesang approved these changes

2022-04-20 04:42 UTC, merged